services:
    zawidawie_core.news.controller:
        class: ZawidawieInfo\CoreBundle\Controller\NewsController
        calls:
            -      [ setContainer, ["@service_container"] ]
        tags:
            -      { name: security.secure_service }

    zawidawie_core.ad.controller:
        class: ZawidawieInfo\CoreBundle\Controller\AdController
        calls:
            -      [ setContainer, ["@service_container"] ]
        tags:
            -      { name: security.secure_service }

    zawidawie_core.news.form:
        class: Symfony\Component\Form\Form
        factory_service: form.factory
        factory_method: create
        arguments:
            -      @zawidawie_core.news.form.type

    zawidawie_core.news.form.type:
        class: ZawidawieInfo\CoreBundle\Form\NewsType

    zawidawie_core.news.form.handler:
        class: ZawidawieInfo\CoreBundle\Form\Handler\NewsFormHandler
        scope: request
        arguments:
            -      @zawidawie_core.news.form
            -      @request
            -      @service_container

    zawidawie_core.news.listener:
        class: ZawidawieInfo\CoreBundle\Listener\NewsRssUpdater
        tags:
            - { name: doctrine.event_listener, event: postPersist }
        arguments:
            -      @nekland_feed.factory
            
    zawidawie_core.tag_manager:
        class: ZawidawieInfo\CoreBundle\Entity\TagManager
        arguments:
            -      @doctrine.orm.entity_manager
            -      %fpn_tag.entity.tag.class%
            -      %fpn_tag.entity.tagging.class%
            -      @fpn_tag.slugifier