imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@ZawidawieInfoCoreBundle/Resources/config/map.xml" }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
           jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
           jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_user:
    db_driver: orm
    firewall_name: main
    use_listener: true
    user_class: ZawidawieInfo\CoreBundle\Entity\User
    registration:
        form:
            type: zawidawie_user_registration

herzult_forum:
    db_driver: orm # can be orm or odm
    class:
        model:
            category:   ZawidawieInfo\ForumBundle\Entity\ForumCategory
            topic:      ZawidawieInfo\ForumBundle\Entity\ForumTopic
            post:       ZawidawieInfo\ForumBundle\Entity\ForumPost
#             user:       ZawidawieInfo\CoreBundle\Entity\User
        controller:
            topic:      ZawidawieInfo\ForumBundle\Controller\TopicController
            post:       ZawidawieInfo\ForumBundle\Controller\PostController
        form:
            post:       ZawidawieInfo\ForumBundle\Form\PostFormType
            first_post: ZawidawieInfo\ForumBundle\Form\PostFormType
        blamer:
            post:       ZawidawieInfo\ForumBundle\Blamer\PostBlamer
        twig:
            extension:  ZawidawieInfo\ForumBundle\Twig\ForumExtension
    paginator:
        topics_per_page: 10
        posts_per_page: 10
        search_results_per_page: 10

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

avalanche_imagine:
    web_root:     %kernel.root_dir%/../web
    cache_prefix: imagine
    driver:       gd
    filters:
        thumbnail:
            type:    thumbnail
            options: { size: [150, 113], mode: outbound }
        thumbnail_medium:
            type:    thumbnail
            options: { size: [500, 375], mode: outbound }
        news_stripe:
            type:    thumbnail
            options: { size: [550, 200], mode: outbound }
        article_stripe:
            type:    thumbnail
            options: { size: [350, 150], mode: outbound }

vich_geographical:
    db_driver: orm

fos_comment:
    db_driver: orm
    class:
        model:
            comment: ZawidawieInfo\CoreBundle\Entity\Comment
            thread: ZawidawieInfo\CoreBundle\Entity\Thread
#     service:
#         blamer:
#             comment: fos_comment.blamer.comment.security

fpn_tag:
    model:
        tag_class: ZawidawieInfo\CoreBundle\Entity\Tag
        tagging_class: ZawidawieInfo\CoreBundle\Entity\Tagging

nekland_feed:
    feeds:
        articles:
            class:        ZawidawieInfo\CoreBundle\Entity\Article
            title:       'Aktualności z serwisu Zawidawie.info'
            description: 'Najważniejsze wiadomości z Psiego Pola i okolic'
            url:         'homepage'
            language:    'pl'
            filename:    "aktualnosci.|format|"

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    common.twig.extension:
        class: ZawidawieInfo\CoreBundle\Twig\CommonExtension
        tags:
            - { name: twig.extension }
    sonata.admin.item:
        class: ZawidawieInfo\CoreBundle\Admin\ItemAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: sonata_blog, label: Obiekty }
        arguments: [null, ZawidawieInfo\CoreBundle\Entity\Item, SonataAdminBundle:CRUD]
    sonata.admin.article:
        class: ZawidawieInfo\CoreBundle\Admin\ArticleAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: sonata_blog, label: Artykuły }
        arguments: [null, ZawidawieInfo\CoreBundle\Entity\Article, SonataAdminBundle:CRUD]
    sonata.admin.catalog:
        class: ZawidawieInfo\CoreBundle\Admin\CatalogItemAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: sonata_blog, label: Firmy }
        arguments: [null, ZawidawieInfo\CoreBundle\Entity\CatalogItem, SonataAdminBundle:CRUD]
    sonata.admin.news_article:
        class: ZawidawieInfo\CoreBundle\Admin\ArticlePhotoAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: sonata_blog, label: Foty do artykułów }
        arguments: [null, ZawidawieInfo\CoreBundle\Entity\ArticlePhotoReference, SonataAdminBundle:CRUD]
    pagerfanta.view.custom:
        class: ZawidawieInfo\PagerBundle\View\CustomView
        public: false
        tags: [{ name: pagerfanta.view, alias: custom }]

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss: